import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from '@clerk/themes'
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/ui/Footer";
import theme from "./theme";
import { ChakraProvider } from "@chakra-ui/react";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "AI-powered Interview Preparation",
  description: "Generated by Jonas Duncan",
  icons: {
    icon: [
      {
        url: '/favicon.png',
        href: '/favicon.png',
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        layout: {
          unsafe_disableDevelopmentModeWarnings: true,
        },
        elements: {
          footerPagesLink: "hidden",
        },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <ChakraProvider theme={theme}>
            <Toaster />
            {children}
            {/* <Footer className="footer" /> */}
          </ChakraProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
